# Generated by Django 2.2.4 on 2019-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190809_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('m', '모델'), ('g', '사진작가'), ('p', '일반인')], max_length=6, null=True, verbose_name='역할'),
        ),
    ]
