# Generated by Django 2.2.4 on 2019-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190809_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buleanito',
            field=models.BooleanField(choices=[(1, 'si'), (2, 'no')], default=1),
        ),
    ]
