# Generated by Django 2.2.4 on 2019-08-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_buleanito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='buleanito',
        ),
    ]
