# Generated by Django 2.2.4 on 2019-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20190810_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_model',
            field=models.NullBooleanField(verbose_name='모델'),
        ),
    ]
