# Generated by Django 2.2.4 on 2019-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190810_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_photographer',
            field=models.BooleanField(default=False, help_text='안녕하세요', verbose_name='사진작가'),
        ),
    ]
