# Generated by Django 2.2.4 on 2019-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_is_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_men',
            field=models.BooleanField(default=False, verbose_name='남성'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_women',
            field=models.BooleanField(default=False, verbose_name='여성'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_photographer',
            field=models.BooleanField(default=False, verbose_name='사진작가'),
        ),
    ]
